site_name: TigerGraph.js

nav:
  - index.md
  - "Docs":
    - Main/vertex.md
    - Main/edge.md
    - Main/query.md
    - Main/misc.md
  - contribute.md
  - license.md

theme: material

extra_css:
  - extra.css

repo_url: https://github.com/TigerGraph-DevLabs/Tigergraph.js
